### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by TwistedModding** [cuyima/EnemyReleveler#1]
This doesn't seem to be working from what I can tell. The zedit version seems to be working just fine, but I can't seem to figure this one out(if it's even working) same config on both versions (synthesis and zedit) but yours doesnt seem to work. Might be worth to take a look at this.

**Comment by TwistedModding** [comment]
Update, it just doesnt work on the most recent version of synthesis, matching the versions fixes it.

**Comment by cuyima** [comment]
While there haven't been any changes that would have broken the patcher I updated it to the latest API regardless.
